[tool.pytest.ini_options]
markers = [
  "integration: marks tests as integration tests (may require external dependencies)",
]
testpaths = ["tests/"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*", "test"]

[tool.ruff]
indent-width = 2
line-length = 99
